player_list = [
"JJ Roy",
"J Patraj",
"CM Wright",
"TT Samaraweera",
"Shapoor Zadran",
"MR Gillespie",
"SMSM Senanayake",
"Rashid Khan",
"J Nyumbu",
"WP Masakadza",
"Yasir Hameed",
"Mahmudullah",
"Imran Tahir",
"MA Parker",
"IH Romaine",
"CD McMillan",
"MF Maharoof",
"Wahab Riaz",
"JPR Lamsam",
"Abdul Shakoor",
"NM Carter",
"TL Best",
"Kabir Ali",
"AF Buurman",
"RP Singh",
"Jahurul Islam",
"BJ Patel",
"VD Philander",
"DR Smith",
"TC Mutombodzi",
"JP Duminy",
"Abdul Jabbar",
"RD Steede",
"S Sharif",
"KO Meth",
"S Jyoti",
"MS Atapattu",
"AP Devcich",
"DF Watts",
"KK Nair",
"Sohail Khan",
"FH Edwards",
"MN Waller",
"D Gough",
"LMP Simmons",
"JM Kemp",
"KL Rahul",
"WP Saha",
"RMS Eranga",
"Zaheer Maqsood",
"PD McGlashan",
"KA Pollard",
"GH Dockrell",
"GD McGrath",
"Mohammad Kashif",
"P Mustard",
"Bilal Asif",
"DC Thomas",
"BR Dorey",
"AR Cusack",
"TG Southee",
"J Blackwood",
"BP Loots",
"AJ Hall",
"GM Strydom",
"AB Dinda",
"PVD Chameera",
"D Daesrath",
"S Weerakoon",
"Qaiser Ali",
"Waqas Barkat",
"Mohammad Hafeez",
"DR Tuffey",
"DW Steyn",
"Jubair Hossain",
"TC Bastiampillai",
"RJ Harris",
"SC Ganguly",
"Asad Ali",
"KAJ Roach",
"Shamsur Rahman",
"Shahriar Nafees",
"K Weeraratne",
"DR Chumney",
"CR Woakes",
"R McLaren",
"MK Pandey",
"SF Mire",
"Mustafizur Rahman",
"Abdur Rehman",
"AM Ellis",
"BJ Watling",
"JE Root",
"AM Phangiso",
"SW Tait",
"Abdul Razzaq",
"Aftab Ahmed",
"Rohan Mustafa",
"MMA Jonkman",
"JW Hastings",
"NR Kumar",
"LD Chandimal",
"A Nel",
"JJ van der Wath",
"RD Shah",
"Tamim Iqbal",
"KO Otieno",
"K Rabada",
"Mehrab Hossain jnr",
"AM Rahane",
"AG Prince",
"Shahzaib Hasan",
"JH Stander",
"Gulbadin Naib",
"NJ Astle",
"J Edness",
"Mohammad Salman",
"M Vijay",
"DG Brownlie",
"CJ Jordan",
"JM Bairstow",
"ML Nkala",
"Zafar Gohar",
"Samiullah Khan",
"HJH Marshall",
"Mirwais Ashraf",
"SM Pollock",
"Kamran Akmal",
"DJ Reekers",
"Junaid Siddique",
"SS Tiwary",
"SD Outerbridge",
"JD Ryder",
"JS Paris",
"NV Ojha",
"KL Tucker",
"D Ganga",
"Mohammad Yousuf",
"Shoaib Malik",
"Amjad Javed",
"K Kamyuka",
"Nadeem Ahmed",
"VAB Tewarie",
"TM Odoyo",
"RM Haq",
"DA Gunawardene",
"CK Kapugedera",
"CL White",
"KDK Vithanage",
"P Connell",
"Amjad Ali",
"Imrul Kayes",
"PD Collingwood",
"M Morkel",
"T Thushara",
"PJ Ingram",
"T Kamungozi",
"A Shahzad",
"SR Waters",
"SJ Harmison",
"LM Jongwe",
"Junaid Siddiqui",
"Umar Amin",
"RDM Leverock",
"DA Minors",
"Samiullah Shenwari",
"Anshuman Rath",
"R Clarke",
"CT Tremlett",
"PJ Forrest",
"Abul Hasan",
"Ahmed Raza",
"R Rampaul",
"PJC Hoffmann",
"Dhiman Ghosh",
"Bilawal Bhatti",
"JDF Vandersay",
"RW Chakabva",
"DS Smith",
"Mohammad Amir",
"RL Bhudia",
"AJ Redmond",
"NM Lyon",
"LE Plunkett",
"Shakib Al Hasan",
"IDR Bradshaw",
"SR Thompson",
"A Zampa",
"DPMD Jayawardene",
"HMRKB Herath",
"CD Cumming",
"Usman Limbada",
"KH Butt",
"A Balbirnie",
"MJ Clarke",
"PJK Mooney",
"N Madziva",
"NM Odhiambo",
"JAR Blain",
"BB McCullum",
"NL McCullum",
"KJ Abbott",
"Iftikhar Anjum",
"PL Harris",
"F Kasteni",
"WTS Porterfield",
"A Martin",
"WU Tharanga",
"S Tyagi",
"BA Westdijk",
"MP Stoinis",
"N M'shangwe",
"H Davids",
"K Karate",
"LRPL Taylor",
"JDP Oram",
"RT Crandon",
"PJ Cummins",
"CH Gayle",
"Inzamam-ul-Haq",
"DLS van Bunge",
"SL Malinga",
"TE Tucker",
"SW Masakadza",
"EC Rainsford",
"Syed Rasel",
"MS Sinclair",
"Sikandar Raza",
"Imran Nazir",
"DE Bernard",
"Khaled Mashud",
"RJ Sidebottom",
"MS Dhoni",
"KTGD Prasad",
"JM Davison",
"T Mishra",
"Hasti Gul",
"HK Bennett",
"S Sreesanth",
"J Anderson",
"GR Codrington",
"KM Dabengwa",
"Rahmat Shah",
"MH Cross",
"ND McKenzie",
"ST Gabriel",
"MK Tiwary",
"A Mithun",
"RD McCann",
"Irfan Sajid",
"Asad Shafiq",
"WF Stelling",
"PR Stirling",
"BA Parchment",
"OL Pitcher",
"D Wiese",
"TG Gordon",
"MB Loye",
"MD Gunathilaka",
"SP Terry",
"SM Katich",
"Hamza Hotak",
"NM Coulter-Nile",
"Y Punja",
"U Bhatti",
"AN Kervezee",
"Mithun Ali",
"Dawlat Zadran",
"VS Solanki",
"Imad Wasim",
"RAJ Smith",
"R Dhawan",
"AJ Strauss",
"Mohammad Sami",
"Noor-ul-Haq",
"MA Wood",
"Soumya Sarkar",
"A Codrington",
"HH Dippenaar",
"AA Noffke",
"Umair Ali",
"BJ McCarthy",
"SW Poynter",
"CJ Chibhabha",
"AN Petersen",
"PKD Chase",
"ST Finn",
"SJ Benn",
"DI Allan",
"WK McCallan",
"JM Anderson",
"AD Mascarenhas",
"A Flintoff",
"D Soraine",
"Anwar Ali",
"MR Swart",
"RM West",
"E Otieno",
"WPUJC Vaas",
"SMA Priyanjan",
"TAM Siriwardana",
"HA Varaiya",
"BKG Mendis",
"M Ntini",
"Mohammad Rizwan",
"AN Cook",
"AJ Ireland",
"Mohammed Shami",
"AJ Finch",
"Tapash Baisya",
"JS Patel",
"JJ Celestine",
"RML Taylor",
"Ahmed Shehzad",
"I Sharma",
"JEC Franklin",
"Arshad Ali",
"MA Carberry",
"JH Davey",
"MJ North",
"JR Hopes",
"MN van Wyk",
"JOA Gordon",
"CT Mutombodzi",
"Javed Omar",
"CK Kruger",
"Mahbubul Alam",
"TBM de Leede",
"NJ O'Brien",
"KD Shah",
"PA Patel",
"SR Clark",
"TM Dowlin",
"M Zondeki",
"JO Ngoche",
"HS Baidwan",
"JC Buttler",
"HM Nicholls",
"A Nehra",
"B Lee",
"S Dhawan",
"MG Johnson",
"KP Pietersen",
"DJ Cullen",
"Enamul Haque jnr",
"PJ Ongondo",
"TWM Latham",
"Arshad Khan",
"T Duffin",
"Suhrawadi Shuvo",
"MEK Hussey",
"J Lewis",
"JA Burns",
"Usman Salahuddin",
"SE Bond",
"MS Chapman",
"Khalid Latif",
"GB Hogg",
"JL Ontong",
"AR Patel",
"C Zhuwao",
"GC Wilson",
"Irfan Ahmed",
"Fawad Ahmed",
"AR White",
"MS Gony",
"RP Arnold",
"MDKJ Perera",
"RE van der Merwe",
"N Dickwella",
"JE Taylor",
"Ehsan Adil",
"NO Miller",
"Haris Sohail",
"Azhar Ali",
"RK Whelan",
"Danish Kaneria",
"RR Rossouw",
"T Mupariwa",
"Izatullah Dawlatzai",
"JP Faulkner",
"SM Davies",
"AA Obanda",
"DR Martyn",
"GA Lamb",
"NT Pascal",
"Mohammad Irfan",
"Sarfraz Ahmed",
"Shafiul Islam",
"Yamin Ahmadzai",
"LR Johnson",
"GD Elliott",
"JR Hazlewood",
"MP Vaughan",
"KM Jadhav",
"DO Obuya",
"KV Sharma",
"SR Watson",
"HD Rutherford",
"G Gambhir",
"PDRL Perera",
"DM Bravo",
"RAS Lakmal",
"F Mutizwa",
"LJ Wright",
"Nazmul Hossain",
"AS Hansra",
"PA van Meekeren",
"AC Gilchrist",
"V Sehwag",
"Tanvir Ahmed",
"PG Fulton",
"RS Higgins",
"Afzaal Haider",
"JWM Dalrymple",
"IS Sodhi",
"Khurram Manzoor",
"MJ Cosgrove",
"Tabarak Dar",
"Nawroz Mangal",
"Shoaib Akhtar",
"Hammad Azam",
"JD Unadkat",
"WW Hinds",
"MA Starc",
"Rahat Ali",
"MM Sharma",
"MC Sorensen",
"CS MacLeod",
"BCJ Cutting",
"D Langford-Smith",
"N Deonarine",
"MS Panesar",
"SM Warnapura",
"LHD Dilhara",
"RJ Peterson",
"FDM Karunaratne",
"B Zuiderent",
"JH Kallis",
"AB Barath",
"KA Edwards",
"Khaliq Dad",
"GS Sandhu",
"Nasir Jamal",
"Faisal Iqbal",
"Hashmatullah Shahidi",
"AC Voges",
"P Utseya",
"BTJ Wheal",
"DT Johnston",
"Sami Aslam",
"C Kieswetter",
"SK Raina",
"T Taibu",
"SL Stewart",
"BA Stokes",
"PW Borren",
"LJ Woodcock",
"J Louw",
"Mohammad Talha",
"HJW Gardiner",
"HS Modi",
"Elias Sunny",
"MO Jones",
"TMK Mawoyo",
"GH Worker",
"AL Kandappah",
"MJ Hoggard",
"Sohag Gazi",
"PA Desai",
"YS Chahal",
"RS Bopara",
"Adnan Akmal",
"Junaid Khan",
"IS Billcliff",
"H Osinde",
"DBL Powell",
"Mohammad Asif",
"Usman Ghani",
"RN Lewis",
"Munir Dar",
"DJG Sammy",
"Aamer Yamin",
"Raza-ur-Rehman",
"JK Kamande",
"Sabbir Rahman",
"CJ Smith",
"R Ashwin",
"KD Karthik",
"Sohail Tanvir",
"NB Mahwire",
"CJ Ferguson",
"Rubel Hossain",
"KW Richardson",
"Mohammad Tauqir",
"ZE Surkari",
"GJ Maxwell",
"EP Thompson",
"GJ Hopkins",
"Mosharraf Hossain",
"CO Obuya",
"MT Chinouya",
"R Gunasekera",
"CJ Anderson",
"Kamran Hussain",
"MJ McClenaghan",
"DA Miller",
"J Botha",
"GB Brent",
"DR Flynn",
"OA Shah",
"LN Onyango",
"GC Smith",
"KED Carroll",
"Mansoor Amjad",
"VJ Kingma",
"DS Kulkarni",
"UT Yadav",
"CJO Smith",
"PA Jaques",
"PJ Moor",
"D Ramdin",
"SE Findlay",
"L Sreekumar",
"Ankur Sharma",
"G Onions",
"DAJ Bracewell",
"ME Trescothick",
"Zakiullah Zaki",
"RJ Trott",
"NLTC Perera",
"GI Maiden",
"N Kruger",
"MJ Prior",
"Yuvraj Singh",
"AF Milne",
"Arafat Sunny",
"T van der Gugten",
"PA Browne",
"H Masakadza",
"Azhar Mahmood",
"L Balaji",
"FL Reifer",
"Faisal Hossain",
"AD Poynter",
"DR Lockhart",
"Fahad Alhashmi",
"MH Yardy",
"JL Denly",
"MJ Mason",
"MA Leask",
"Krishna Chandran",
"MA Ouma",
"IG Butler",
"BMAJ Mendis",
"LP van Troost",
"AR Adams",
"WD Balaji Rao",
"MM Patel",
"A Bagai",
"VRV Singh",
"MJG Rippon",
"A Symonds",
"MM Ali",
"R Telemachus",
"PA Nixon",
"CB Mpofu",
"AM Nayar",
"N Ncube",
"EC Joyce",
"Mashrafe Mortaza",
"JN Mohammed",
"Aizaz Cheema",
"JAH Marshall",
"MJ Guptill",
"CD Collymore",
"Haseeb Amjad",
"SP Fleming",
"B Laughlin",
"Dawlat Ahmadzai",
"MS Wade",
"AK Perera",
"DR Briggs",
"R Dravid",
"SW Billings",
"UT Khawaja",
"M de Lange",
"AS Luseno",
"Asghar Stanikzai",
"JP Bray",
"N Pradeep",
"JD Nel",
"T Muzarabani",
"MJ Henry",
"GS Ballance",
"Saeed Ajmal",
"SP Narine",
"Mohammad Ashraful",
"I Wardlaw",
"BN Cooper",
"JWA Taylor",
"Zulfiqar Babar",
"T Panyangara",
"UDU Chandana",
"Hamid Hassan",
"SR Patel",
"RT Lyons",
"TV Mufambisi",
"Taskin Ahmed",
"NM Hauritz",
"A Kumble",
"SS Cottrell",
"AD Hales",
"Nasir Aziz",
"SD Parry",
"Salman Farooq",
"SP Patil",
"LS Baker",
"SS Pathirana",
"Shuvagoto Hom",
"WB Rankin",
"Tanwir Afzal",
"PJ Hughes",
"Ziaur Rahman",
"Al-Amin Hossain",
"GH O'Brien",
"Raza Hasan",
"ID Blackwell",
"PA Hitchcock",
"Skhawat Ali",
"Naeem Islam",
"KOA Powell",
"AR Berenger",
"Rajin Saleh",
"K Whatham",
"BRM Taylor",
"Abdur Razzak",
"CJ McKay",
"XJ Doherty",
"AR McBrine",
"MA Vermeulen",
"ML Lewis",
"PP Chawla",
"AC Agar",
"Najibullah Zadran",
"RA Jadeja",
"CR Ervine",
"CRD Fernando",
"NT Broom",
"GD Drummond",
"Raqibul Hasan",
"HM Amla",
"GM Hamilton",
"RW Price",
"H Durham",
"I Udana",
"RN ten Doeschate",
"Asif Iqbal (1)",
"HP Rinke",
"V Sibanda",
"ML Patel",
"CA Pujara",
"Sharafuddin Ashraf",
"D Elgar",
"ES Szwarczynski",
"E Katchay",
"EJG Morgan",
"DJ Hussey",
"SM Boland",
"C Munro",
"S Matsikenyeri",
"CK Coventry",
"BJ Diamanti",
"Saqib Ali",
"IE O'Brien",
"JL Pattinson",
"GJ Bailey",
"CMW Read",
"DM Richards",
"IA Karim",
"GA Manou",
"CKB Kulasekara",
"KT Sandher",
"Sharjeel Khan",
"PG Gillespie",
"Zahid Shah",
"Naved-ul-Hasan",
"HF Gurney",
"Q de Kock",
"Nasir Hossain",
"Zahid Hussain",
"MS Tshabalala",
"BJ Hodge",
"DJ Bravo",
"CH Morris",
"TJ Heggelman",
"GJ Batty",
"JM How",
"Pankaj Singh",
"Gurkeerat Singh",
"AW Mathieson",
"LPC Silva",
"Mohammad Iqbal",
"SB Styris",
"RT Ponting",
"CS Baugh",
"Yasir Arafat",
"W Barresi",
"D Bishoo",
"DT Tiripano",
"M Kartik",
"JM Vince",
"Alok Kapali",
"AD Mathews",
"TD Paine",
"AM Blignaut",
"Salman Faris",
"JA Rudolph",
"AM Samad",
"KC Hodsoll",
"BW Hilfenhaus",
"Anamul Haque",
"V Permaul",
"AU Rashid",
"AA Mulla",
"PC Connell",
"T Shamsi",
"Dolar Mahmud",
"S Badrinath",
"Babar Azam",
"Mohammad Naveed",
"DT Christian",
"TN de Grooth",
"BAW Mendis",
"MKDI Amerasinghe",
"JC Tredwell",
"KJ Coetzer",
"MD Bates",
"PP Ojha",
"MV Boucher",
"DI Joyce",
"Aman Ali",
"SI Mahmood",
"J Mubarak",
"SM Sharif",
"Saqlain Haider",
"M Pushpakumara",
"DCC Borden",
"NN Odhiambo",
"Salman Butt",
"JW Dernbach",
"Litton Das",
"F Behardien",
"Kamran Shazad",
"J Smits",
"S Randiv",
"Habibul Bashar",
"Aftab Alam",
"J Charles",
"IPP Batuwitarachchi",
"HMCM Bandara",
"SPD Smith",
"Imran Farhat",
"DE Bollinger",
"Mominul Haque",
"RR Sarwan",
"A Mishra",
"KD Mills",
"MAA Jamil",
"R Flannigan",
"B Geeves",
"NFI McCallum",
"GP Swann",
"DA Warner",
"MBS Jonkman",
"SKW Kelly",
"GH Bodi",
"P Kumar",
"TR Ambrose",
"C de Grandhomme",
"NW Bracken",
"AJ McKay",
"HDRL Thirimanne",
"RG Aga",
"SCJ Broad",
"Hamza Tariq",
"BV Vitori",
"GO Jones",
"WCA Ganegama",
"AC Cummins",
"SR Tendulkar",
"G Goudie",
"Rokhan Barakzai",
"CD de Lange",
"PM Siddle",
"JJ Krejza",
"Khurram Khan",
"SO Tikolo",
"M Shezi",
"ML Udawatte",
"Manjural Islam Rana",
"IK Pathan",
"S Dhaniram",
"GC Tonge",
"PHT Kaushal",
"DL Vettori",
"Shaiman Anwar",
"KS Williamson",
"MDK Perera",
"KM Jarvis",
"Khurram Chohan",
"MJ Lumb",
"JS Ababu",
"Babar Hayat",
"BJ Haddin",
"Younis Khan",
"KJ O'Brien",
"Abdur Rauf",
"L Vincent",
"RG Sharma",
"KC Sangakkara",
"WD Parnell",
"J Theron",
"Y Venugopal Rao",
"STR Binny",
"MJ Santner",
"PLS Gamage",
"RK Kleinveldt",
"BP Nash",
"JL Carter",
"RD Berrington",
"Fayyaz Ahmed",
"BP Kruger",
"XM Marshall",
"CD Wallace",
"Mohammad Shahzad",
"Mohammad Nabi",
"TLW Cooper",
"N Dutta",
"JF Mooney",
"F du Plessis",
"Shami Ahmed",
"JJ Bumrah",
"S Chanderpaul",
"RJW Topley",
"GA Rogers",
"AR Pitcher",
"SC Williams",
"AD Russell",
"Afsar Zazai",
"RR Watson",
"R Mutumbami",
"Tushar Imran",
"SJ Myburgh",
"CR Brathwaite",
"AT Rayudu",
"M Kaif",
"PC de Silva",
"E Schiferli",
"Zeeshan Siddiqi",
"Gulbodin Naib",
"KS Lokuarachchi",
"D Mongia",
"KMC Bandara",
"CL Cairns",
"KMDN Kulasekara",
"Raees Ahmadzai",
"MW Machan",
"PL Mommsen",
"RS Morton",
"IJL Trott",
"Nizakat Khan",
"Shafiqullah",
"Najeeb Amar",
"MJ Fourie",
"RV Uthappa",
"JJ Atkinson",
"Shahadat Hossain",
"SHT Kandamby",
"S Chattergoon",
"VR Aaron",
"DK Butler",
"MR Marsh",
"Noor Ali Zadran",
"TM Dilshan",
"TA Boult",
"VVS Laxman",
"AO Suji",
"MM Iqbal",
"R Vinay Kumar",
"ML Hayden",
"FRJ Coleman",
"RJ Nicol",
"M Muralitharan",
"AG Cremer",
"Hashmatullah Shaidi",
"Z Khan",
"OO Bascome",
"N Mushangwe",
"S Thuraisingam",
"Mohammad Shahzad (2)",
"RR Powar",
"AC Botha",
"Adeel Raja",
"Mushfiqur Rahim",
"CS Martin",
"GW Flower",
"V Kohli",
"IR Bell",
"Mohammad Rafique",
"R Sharma",
"LL Tsotsobe",
"AB Agarkar",
"RR Emrit",
"S Mukuddem",
"Aizaz Khan",
"DSNFG Jayasuriya",
"Amir Hamza",
"LOB Cann",
"KAD Hurdle",
"AM Guruge",
"B Kumar",
"Shahid Afridi",
"Umar Gul",
"CAK Walton",
"Saad Nasim",
"JO Holder",
"Taufeeq Umar",
"NS Poonia",
"W Jaffer",
"Iftikhar Ahmed",
"H Patel",
"DL Hemp",
"YK Pathan",
"CK Langeveldt",
"DR Brown",
"UWMBCA Welegedara",
"GJ McCarter",
"Karim Sadiq",
"G Chapple",
"ADS Fletcher",
"VB van Jaarsveld",
"ADJ Pitcher",
"Javed Ahmadi",
"S Prasanna",
"EJ Richardson",
"Misbah-ul-Haq",
"Bazid Khan",
"Robiul Islam",
"SE Marsh",
"MC Henriques",
"Nasir Jamshed",
"CA Young",
"JDS Neesham",
"Mudassar Bukhari",
"E Chigumbura",
"SC Meaker",
"HH Gibbs",
"BB Chari",
"A van der Merwe",
"Sami Faridi",
"Harbhajan Singh",
"NG Jones",
"LE Bosman",
"RR Patel",
"BB Sran",
"TS Nethula",
"Nazimuddin",
"T Maruma",
"Liton Das",
"Fawad Alam",
"TT Bresnan",
"TL Chatara",
"TJ Murtagh",
"GJP Kruger",
"DJ Willey",
"D Mohammed",
"CR Foggo",
"Sohaib Maqsood",
"AB de Villiers",
"AC Evans",
"GEF Barnett",
"ST Jayasuriya",
"KHRK Fernando",
"TM Head",
"JJ Tucker",
"Farhad Reza",
"Umar Akmal",
"Yasir Shah",
"Rizwan Cheema",
"L Ronchi",
"CA Ingram",
"Zulqarnain Haider",
"BM Wheeler",
"TS Chisoro",
"MN Samuels",
"MD Shanaka",
"GW Aldridge",
"CK Hooper",
"JA Morkel",
"BC Lara",
"PM Seelaar",
"DP Hyatt",
"SO Ngoche",
"Parvez Rasool"
]

team_list = [
"Bermuda",
"New Zealand",
"Ireland",
"Africa XI",
"England",
"Hong Kong",
"Zimbabwe",
"Pakistan",
"United Arab Emirates",
"India",
"South Africa",
"Sri Lanka",
"West Indies",
"Afghanistan",
"Kenya",
"Bangladesh",
"Scotland",
"Asia XI",
"Australia",
"Canada",
"Netherlands"
]

venue_list = {
"University Oval":"New Zealand",
"Melbourne Cricket Ground":"Australia",
"Adelaide Oval":"Australia",
"Bert Sutcliffe Oval":"New Zealand",
"McLean Park":"New Zealand",
"Providence Stadium":"Guyana",
"The Village, Malahide":"Ireland",
"National Cricket Stadium, St George's":"Grenada",
"Gaddafi Stadium":"Pakistan",
"Keenan Stadium":"India",
"Sector 16 Stadium":"India",
"Sir Vivian Richards Stadium, North Sound":"Antigua and Barbuda",
"Khan Shaheb Osman Ali Stadium":"Bangladesh",
"Arnos Vale Ground, Kingstown":"Saint Vincent and the Grenadines",
"Jade Stadium":"New Zealand",
"Bellerive Oval":"Australia",
"Queen's Park Oval, Port of Spain":"Trinidad and Tobago",
"Clontarf Cricket Club Ground":"Ireland",
"Sinhalese Sports Club Ground":"Sri Lanka",
"Buffalo Park":"South Africa",
"Peter Burge Oval":"Australia",
"Trent Bridge":"England",
"Mannofield Park":"Scotland",
"Nahar Singh Stadium":"India",
"Nehru Stadium":"India",
"North Marine Road Ground":"England",
"Queens Sports Club":"Zimbabwe",
"Southend Club Cricket Stadium":"Pakistan",
"Boland Park":"South Africa",
"Sydney Cricket Ground":"Australia",
"Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa":"Sri Lanka",
"Niaz Stadium, Hyderabad":"India",
"Chevrolet Park":"South Africa",
"Captain Roop Singh Stadium":"India",
"Westpac Stadium":"New Zealand",
"Seddon Park":"New Zealand",
"Saxton Oval":"New Zealand",
"Pallekele International Cricket Stadium":"Sri Lanka",
"R Premadasa Stadium":"Sri Lanka",
"Rajiv Gandhi International Stadium, Uppal":"India",
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium":"India",
"Civil Service Cricket Club, Stormont":"Northern Ireland",
"Arbab Niaz Stadium":"Pakistan",
"Observatory Lane, Rathmines":"Ireland",
"Dubai Sports City Cricket Stadium":"United Arab Emirates",
"SuperSport Park":"South Africa",
"Haslegrave Ground":"England",
"Mombasa Sports Club Ground":"Kenya",
"Jaffery Sports Club Ground":"Kenya",
"Madhavrao Scindia Cricket Ground":"India",
"Cobham Oval (New)":"New Zealand",
"Multan Cricket Stadium":"Pakistan",
"Saurashtra Cricket Association Stadium":"India",
"MA Chidambaram Stadium, Chepauk":"India",
"Sophia Gardens":"Wales",
"Kennington Oval":"England",
"Eden Gardens":"India",
"Gymkhana Club Ground":"Kenya",
"Chittagong Divisional Stadium":"Bangladesh",
"Reliance Stadium":"India",
"Holkar Cricket Stadium":"India",
"Louth Cricket Club":"England",
"ICC Academy":"United Arab Emirates",
"Edgbaston":"England",
"Harare Sports Club":"Zimbabwe",
"National Stadium":"Pakistan",
"North Sydney Oval":"Australia",
"Green Park":"India",
"Hagley Oval":"New Zealand",
"ICC Global Cricket Academy":"United Arab Emirates",
"YMCA Cricket Club":"Ireland",
"Himachal Pradesh Cricket Association Stadium":"India",
"Rangiri Dambulla International Stadium":"Sri Lanka",
"AMI Stadium":"New Zealand",
"Bradman Oval":"Australia",
"Sir Paul Getty's Ground":"England",
"Western Australia Cricket Association Ground":"Australia",
"Antigua Recreation Ground, St John's":"Antigua and Barbuda",
"Zahur Ahmed Chowdhury Stadium":"Bangladesh",
"Sabina Park, Kingston":"Jamaica",
"JSCA International Stadium Complex":"India",
"Willowmoore Park":"South Africa",
"Brabourne Stadium":"India",
"Iqbal Stadium":"Pakistan",
"Sedgars Park":"South Africa",
"Shaheed Chandu Stadium":"Bangladesh",
"Titwood":"Scotland",
"OUTsurance Oval":"South Africa",
"Sheikhupura Stadium":"Pakistan",
"Nehru Stadium, Fatorda":"India",
"Sawai Mansingh Stadium":"India",
"Newlands":"South Africa",
"Kensington Oval, Bridgetown":"Barbados",
"Sheikh Abu Naser Stadium":"Bangladesh",
"M Chinnaswamy Stadium":"India",
"Andhra Cricket Association-Visakhapatnam District Cricket Association Stadium":"India",
"Zohur Ahmed Chowdhury Stadium":"Bangladesh",
"Eden Park":"New Zealand",
"Riverside Ground":"England",
"Toronto Cricket":"Canada",
"Lord's":"England",
"Hurstville Oval":"Australia",
"Feroz Shah Kotla":"India",
"Grange Cricket Club Ground, Raeburn Place":"Scotland",
"Wankhede Stadium":"India",
"Marrara Cricket Ground":"Australia",
"Maharani Usharaje Trust Cricket Ground":"India",
"Indian Petrochemicals Corporation Limited Sports Complex Ground":"India",
"Queenstown Events Centre":"New Zealand",
"Vidarbha Cricket Association Ground":"India",
"Basin Reserve":"New Zealand",
"Beausejour Stadium, Gros Islet":"Saint Lucia",
"Dubai International Cricket Stadium":"United Arab Emirates",
"County Ground":"England",
"The Rose Bowl":"England",
"Kingsmead":"South Africa",
"Grace Road":"England",
"St George's Park":"South Africa",
"Sharjah Cricket Stadium":"United Arab Emirates",
"Cambusdoon New Ground":"Scotland",
"Headingley":"England",
"Manuka Oval":"Australia",
"New Wanderers Stadium":"South Africa",
"Kinrara Academy Oval":"Malaysia",
"Shere Bangla National Stadium":"Bangladesh",
"Narayanganj Osmani Stadium":"Bangladesh",
"Maharashtra Cricket Association Stadium":"India",
"Goodyear Park":"South Africa",
"Punjab Cricket Association Stadium, Mohali":"India",
"Brisbane Cricket Ground, Woolloongabba":"Australia",
"VRA Ground":"Netherlands",
"Ruaraka Sports Club Ground":"Kenya",
"Mangaung Oval":"England",
"Sheikh Zayed Stadium":"United Arab Emirates",
"Sardar Patel Stadium, Motera":"India",
"Windsor Park, Roseau":"Dominica",
"Bay Oval":"New Zealand",
"Rawalpindi Cricket Stadium":"Pakistan",
"Old Trafford":"England",
"Maple Leaf North-West Ground":"Canada",
"Warner Park, Basseterre":"Saint Kitts and Nevis",
"Barabati Stadium":"India",
"Senwes Park":"South Africa",
"County Ground, New Road":"England",
"P Saravanamuttu Stadium":"Sri Lanka",
"Boland Bank Park":"South Africa",
"Vidarbha Cricket Association Stadium, Jamtha":"India",
"Sharjah Cricket Association Stadium":"United Arab Emirates",
"Docklands Stadium":"Australia",
"De Beers Diamond Oval":"South Africa"
}